# Form implementation generated from reading ui file 'ui_formats\ana_sayfa.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 451)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_formats\\../assets/logotry.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.btn_hesapla = QtWidgets.QPushButton(parent=Form)
        self.btn_hesapla.setGeometry(QtCore.QRect(20, 150, 331, 28))
        self.btn_hesapla.setObjectName("btn_hesapla")
        self.tbl_kur = QtWidgets.QTableWidget(parent=Form)
        self.tbl_kur.setGeometry(QtCore.QRect(380, 100, 231, 331))
        self.tbl_kur.setRowCount(20)
        self.tbl_kur.setColumnCount(2)
        self.tbl_kur.setObjectName("tbl_kur")
        self.lne_arama = QtWidgets.QLineEdit(parent=Form)
        self.lne_arama.setGeometry(QtCore.QRect(380, 60, 231, 22))
        self.lne_arama.setObjectName("lne_arama")
        self.cmb_secilen2 = QtWidgets.QComboBox(parent=Form)
        self.cmb_secilen2.setGeometry(QtCore.QRect(20, 110, 141, 22))
        self.cmb_secilen2.setEditable(True)
        self.cmb_secilen2.setObjectName("cmb_secilen2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(180, 110, 16, 16))
        self.label.setObjectName("label")
        self.lbl_sonuc = QtWidgets.QLabel(parent=Form)
        self.lbl_sonuc.setGeometry(QtCore.QRect(20, 190, 331, 20))
        self.lbl_sonuc.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lbl_sonuc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.cmb_secilen1 = QtWidgets.QComboBox(parent=Form)
        self.cmb_secilen1.setGeometry(QtCore.QRect(210, 110, 141, 22))
        self.cmb_secilen1.setEditable(True)
        self.cmb_secilen1.setObjectName("cmb_secilen1")
        self.lne_miktar = QtWidgets.QLineEdit(parent=Form)
        self.lne_miktar.setGeometry(QtCore.QRect(20, 60, 331, 22))
        self.lne_miktar.setObjectName("lne_miktar")
        self.wdg_chart = QtWidgets.QWidget(parent=Form)
        self.wdg_chart.setGeometry(QtCore.QRect(20, 220, 331, 201))
        self.wdg_chart.setObjectName("wdg_chart")
        self.wdg_slider = QtWidgets.QWidget(parent=Form)
        self.wdg_slider.setGeometry(QtCore.QRect(-11, -10, 651, 31))
        self.wdg_slider.setObjectName("wdg_slider")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Döviz Takip Ve Hesaplayıcı     Alpha V-0.3"))
        self.btn_hesapla.setText(_translate("Form", "HESAPLA"))
        self.lne_arama.setPlaceholderText(_translate("Form", "Ara"))
        self.label.setText(_translate("Form", "->"))
        self.lbl_sonuc.setText(_translate("Form", "SONUÇ"))
        self.lne_miktar.setPlaceholderText(_translate("Form", "Miktar"))
